### ISSUE TITLE
Multiple Level Json

### ISSUE THREAD

**Issue by qisbic** [Baklap4/DotNetLocalizer#4]
How can I change the code to support reading multiple level json file.

Below,  PageHeader -> Home.

I tried `@localizer["pageHeader.Home"]` but it does not seem to work.

{
  "Language": "Language",
  "NotFoundKeyInCurrentCultureButInOtherFallback": "Key not found1 in current culture ('{0}') but found in other culture (fallback option)",
  "ObjectExampleKey": "Give me an object: '{0}'",
  "OtherKey": "Other key",
  "RequestCultureProvider": "Request Culture Provider",
  "SomeKey": "Some key",

  **"pageHeader": {
    "Home": "Home"**
  }
}

**Comment by Baklap4** [comment]
Hey @qisbic 
Thanks for trying out this library!
Currently the `strings.{culture}.json` files are saved as a `Dictionairy<string, object>` [as can be seen here](https://github.com/Baklap4/DotNetLocalizer/blob/master/src/DotNetLocalizer.Core/Localizer.cs#L15)

While this structure could support nested objects it currently does not since we're just calling `Dictionary<string, object>.TryGetValue()` which will get the value of [the given key](https://github.com/Baklap4/DotNetLocalizer/blob/master/src/DotNetLocalizer.Json/JsonLocalizer.cs#L45-L49) 

You could try to check if the value is of type other than `System.String` if so it's a complex type and you would need to loop through it's properties and get the values for them. This goes on till you've found your deepnested property.

I'd suggest to not do this since this kills the performance of the `TryGetValue()` method which currently is O(1)  (constant). Therefore i'd add these values to the main `strings.{culture}.json`

However if you feel like you can get this method performing feel free to add the code upstream!

# Edit
You might check out this answer on [stackoverflow](https://stackoverflow.com/a/15548722/2724940) for getting nested values from a complex type

**Comment by Baklap4** [comment]
Joo @qisbic 
I've managed to get this working on my local branch, will push the changes in a few 👍 
My question though, why would you want to have this?

**Comment by qisbic** [comment]
Because it's easier to category items.. See an example json below.
I tried your latest codes.. it works perfectly for what I need... thanks!
{
  "app": {
    "Welcome": "Welcome"
  },
  "mainMenu": {
    "Personal": "Personal",
    "Business": "Business",
    "FAQ": "FAQ",
    "ContactUs": "Contact Us",
    "Registration": "Registration",
    "SignUp": "Sign Up",
    "Login": "Login"
  },
  "registrationEmailSent": {
    "Success": "Thank You! A registration email has been sent to your email!",
    "Failed": "An issued has with registration has been encountered, notification has been sent to our administrator. Please try again later at a later time."
  },
  "notFound": {
    "404": "404",
    "PageNotFound": "The page you are looking for does not exist",
    "BackToHome": "Back to home"
  }

**Comment by Baklap4** [comment]
Ahhh i thought so already :) ! You're welcome! If yhere's anything more feel free to file an issue or comment :) glad someone beside me is using this hahah ;)
